export interface LabLocation {
  lab: 'LabCorp' | 'Sonora Quest' | 'LabXpress';
  googlePlaceId: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  servicesOffered: string;
  notes: string;
}

export const LabLocationsData: LabLocation[] = [
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJCxC4mhISK4cRXGdJm8usub8',
    address: '1010 E MCDOWELL STE 201',
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85006',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJJR34iQs_K4cR3F7v0Yl_q9A',
    address: '10815 W MCDOWELL RD 302',
    city: 'AVONDALE',
    state: 'AZ',
    zip: '85323',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJtTG0frs4K4cRknnyxlkgtCI',
    address: '13555 W MCDOWELL RD STE 208',
    city: 'GOODYEAR',
    state: 'AZ',
    zip: '85395',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections\nH pylori breath test',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJFeuDRCRbK4cRQfpWQ2-nvto',
    address: '14418 W MEEKER BLVD BLDG B-104',
    city: 'SUN CITY WEST',
    state: 'AZ',
    zip: '85375',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJ2X5kuuxFK4cRGLaFEInok20',
    address: '15317 W. BELL RD. C102',
    city: 'SURPRISE',
    state: 'AZ',
    zip: '85374',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nH pylori breath test',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJMXTN_4iYK4cRlb1m3_1E3tA',
    address: '16838 E PALISADES PKWY A-101',
    city: 'FOUNTAIN HILLS',
    state: 'AZ',
    zip: '85268',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections\nH pylori breath test',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJeVlgVX4IK4cRrtUzNVjYTpU',
    address: '1950 E SOUTHERN AVE STE 101',
    city: 'TEMPE',
    state: 'AZ',
    zip: '85282',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections\nH pylori breath test',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJoTqeSXesK4cRLRmpPjY7mDc',
    address: '2730 S VAL VISTA DR STE 111',
    city: 'GILBERT',
    state: 'AZ',
    zip: '85296',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJw0KfeFkSK4cRicNxGxVfXvI',
    address: '333 WEST THOMAS RD. 101',
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85013',
    servicesOffered:
      'Routine labwork\nEmployee wellness with body measurement\nRadar (point of collection drug screen)\nPediatric collections\nEmployment drug testing',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJwd2QHHhxK4cRktx9zLgbg1U',
    address: '3815 E BELL RD STE 1450',
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85032',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJq6qqqievK4cRpfONmWYVe6w',
    address: '4001 E BASELINE RD STE 201',
    city: 'GILBERT',
    state: 'AZ',
    zip: '85234',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJA9rtanJpK4cR3D-Okid5gYc',
    address: '5750 W THUNDERBIRD RD STE E580',
    city: 'GLENDALE',
    state: 'AZ',
    zip: '85306',
    servicesOffered:
      'Routine labwork\nEmployee wellness with body measurement\nSaliva alcohol testing\nRadar (point of collection drug screen)\nPediatric collections\nEmployment drug testing',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJN8i9H5unK4cRu7U0ozn8zxU',
    address: '6118 E BROWN RD.',
    city: 'MESA',
    state: 'AZ',
    zip: '85205',
    servicesOffered:
      'Routine labwork\nEmployee wellness with body measurement\nSaliva alcohol testing\nRadar (point of collection drug screen)\nPediatric collections\nEmployment drug testing\nH pylori breath test\nHair collection',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJ3aSLrL4AK4cRsGXOAHrt2s0',
    address: '725 S DOBSON RD STE 103',
    city: 'CHANDLER',
    state: 'AZ',
    zip: '85224',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJ5eZqUtZ1K4cRPNjI_Nzj9NQ',
    address: '8575 E PRINCESS DR STE 119',
    city: 'SCOTTSDALE',
    state: 'AZ',
    zip: '85255',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJF-kdyG5CK4cROxmyfTNxk6U',
    address: '9139 W THUNDERBIRD STE 150',
    city: 'PEORIA',
    state: 'AZ',
    zip: '85381',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement\nPediatric collections',
    notes: '',
  },
  {
    lab: 'LabCorp',
    googlePlaceId: 'ChIJqdjiN0Z1K4cR2t1ulH2qTmg',
    address: '9465 E IRONWOOD SQUARE DR 103',
    city: 'SCOTTSDALE',
    state: 'AZ',
    zip: '85258',
    servicesOffered: 'Routine labwork\nEmployee wellness with body measurement',
    notes: '',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJmd9a1nwEK4cRy6yq9SS0jE8',
    address: '15810 S 45th St, #101',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85048',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ7bYMe_udLIcRzBqRhm8h2tM',
    address: '3624 W Anthem Way, #C-114',
    city: 'Anthem',
    state: 'AZ',
    zip: '85086',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJd_Nxhcy2K4cRK7LavFtlmoI',
    address: '2080 W Southern Ave, #B6',
    city: 'Apache Junction',
    state: 'AZ',
    zip: '85120',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJK1fzoDd1K4cRQ12l38mMYqY',
    address: '3003 Highway 95, #H-81',
    city: 'Bullhead City',
    state: 'AZ',
    zip: '86442',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJYRwwaSShLYcRA6ncT4NE77M',
    address: '2300 W Highway 89A',
    city: 'Sedona',
    state: 'AZ',
    zip: '86336',
    servicesOffered: 'Routine Labs\nPediatric\nInsurance Exam (Exam One)\nQuest Health & Wellness',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJXx7C5aVnKocRdbSbljexDdg',
    address: '1860 E Salk Dr, #A-1',
    city: 'Casa Grande',
    state: 'AZ',
    zip: '85122',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJGUwg1LkAK4cRA5V-v9gi-r4',
    address: '2081 W Frye Rd, #107',
    city: 'Chandler',
    state: 'AZ',
    zip: '85224',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJET1e7GpvK4cRwjS_hObtsaw',
    address: '20414 N 27th Ave, #140',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85027',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJU6jzbxM3LYcR4dx-YsXKsuE',
    address: '1031 N. State Rte. 89',
    city: 'Chino Valley',
    state: 'AZ',
    zip: '86323',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJQ-JFvO4PLYcR1K5Vwvj3LfM',
    address: '203 S. Candy Lane #4-B',
    city: 'Cottonwood',
    state: 'AZ',
    zip: '86326',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ5yQLUkGPLYcRvbejOAS128U',
    address: '1100 N. San Francisco St., Suite C (2nd Floor)',
    city: 'Flagstaff',
    state: 'AZ',
    zip: '86001',
    servicesOffered:
      'Routine Labs\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJzflb-yqPLYcRtN_k21azu_A',
    address: '1515 E Cedar Ave, Bldg. F',
    city: 'Flagstaff',
    state: 'AZ',
    zip: '86004',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJBdg7cIFHKocR5-0AeNLS0CY',
    address: '3325 N Hunt Highway',
    city: 'Florence',
    state: 'AZ',
    zip: '85132',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJy64sB4mYK4cRMY6WdEy16tk',
    address: '13620 N Saguaro Blvd, #150',
    city: 'Fountain Hills',
    state: 'AZ',
    zip: '85268',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJHTsJMg-tK4cRlNchIs-pIMU',
    address: '3530 S Val Vista Dr, Suite B206',
    city: 'Gilbert',
    state: 'AZ',
    zip: '85297',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJq8ebdAOvK4cR-11xVXLmJSk',
    address: '2940 E Banner Gateway Dr, #325',
    city: 'Gilbert',
    state: 'AZ',
    zip: '85234',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJDRPwvIgRK4cR5yzkb9QWjUo',
    address: '2640 W Baseline Rd, #115',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85041',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ-WsL33dxK4cR5nPHwEl56xw',
    address: '3805 E Bell Rd, #1500',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85032',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJga30JckUK4cRsRSUr-xZ3Q8',
    address: '4524 N Maryvale Pkwy, #120',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85031',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJj2sFw9hlK4cRI-V4OWwUOwI',
    address: '3800 W Happy Valley Rd',
    city: 'Glendale',
    state: 'AZ',
    zip: '85310',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJGc2amgo6K4cRXo2CAreK7go',
    address: '9890 S Estrella Pkwy',
    city: 'Goodyear',
    state: 'AZ',
    zip: '85338',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJs6JvI-o4K4cRwLLUu3PXPvU',
    address: '13657 W McDowell Rd, #100',
    city: 'Goodyear',
    state: 'AZ',
    zip: '85395',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJLXTnsIGE1oYRoZLcds18D0I',
    address: '1151 S La Canada, #206',
    city: 'Green Valley',
    state: 'AZ',
    zip: '85614',
    servicesOffered:
      'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJZ6uf7f-pL4cR6UtpUoc36gg',
    address: '702 W Hopi Dr',
    city: 'Holbrook',
    state: 'AZ',
    zip: '86025',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJeRNKhOzdzYARE8gSCCEZbMA',
    address: '2505 Hualapai Mountain Rd, Ste A',
    city: 'Kingman',
    state: 'AZ',
    zip: '86401',
    servicesOffered: 'Routine Labs\nPediatric\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJZ5dVoiLczYARrVx9Ppz1P2U',
    address: '3970 Stockton Hill Rd',
    city: 'Kingman',
    state: 'AZ',
    zip: '86409',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ2z35X4ft0YARNRzu4MPpKR0',
    address: '1964 Mesquite Ave, Unit A',
    city: 'Lake Havasu City',
    state: 'AZ',
    zip: '86403',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJJx21Ei37KocRAaSCvfrGrvE',
    address: '21300 N John Wayne Pkwy, Bldg 3, #106',
    city: 'Maricopa',
    state: 'AZ',
    zip: '85139',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJw5vECZSvK4cRS7TaInXXxr4',
    address: '6344 E Broadway Rd, #118',
    city: 'Mesa',
    state: 'AZ',
    zip: '85206',
    servicesOffered: 'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJW8vFY-s_K4cR9nYCdlH-cJA',
    address: '9321 W Thomas Rd, Suite 105',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85037',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJqR9-z9lsK4cRqpkrXclBlPY',
    address: '2001 W Camelback Rd, #150',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85015',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJjeBI_BANK4cR4B7Kxu7rGQE',
    address: '3132 E Camelback Rd',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85016',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ_WdrzD5uK4cRJug6fYHZzUo',
    address: '550 E Bell Rd',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85022',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJhx3TlApzK4cROvAkn03ffpc',
    address: '11209 N Tatum Blvd, #185',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85028',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ_5a2cs4N1oYRocpCX0FjpMg',
    address: '1848 E Innovation Park Dr',
    city: 'Oro Valley',
    state: 'AZ',
    zip: '85755',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nEmployer Directed Drug Screen\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJXd_ftOQQLIcRmpzRIHSeNI4',
    address: '117 E Main St, Bldg C, #200',
    city: 'Payson',
    state: 'AZ',
    zip: '85541',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJD4vB-e9nK4cRzfjLYDOZxgQ',
    address: '7757 W Deer Valley Rd, #265',
    city: 'Peoria',
    state: 'AZ',
    zip: '85382',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJX6wKkZhfK4cR_nP837hMM40',
    address: '28455 N Vistancia Blvd',
    city: 'Peoria',
    state: 'AZ',
    zip: '85383',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJkaJKE0JCK4cR4gOyqXfPaJo',
    address: '13760 N 93rd Ave, #107',
    city: 'Peoria',
    state: 'AZ',
    zip: '85381',
    servicesOffered: 'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJJY-fHeQHK4cR0cL7G1uBlg8',
    address: '1432 S Dobson Rd, #201',
    city: 'Mesa',
    state: 'AZ',
    zip: '85202',
    servicesOffered: 'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJEy_-khevK4cRtSOEYNAMCWA',
    address: '1425 S Greenfield Rd, #102',
    city: 'Mesa',
    state: 'AZ',
    zip: '85206',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJBY43TJh01oYR9eUGdElVU88',
    address: '1925 W Orange Grove Rd, #100',
    city: 'Tucson',
    state: 'AZ',
    zip: '85704',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJG2yCLOqvK4cRohXPBW968Sw',
    address: '6106 E Brown Rd, #101',
    city: 'Mesa',
    state: 'AZ',
    zip: '85205',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJEeFtENJ21oYRG647GImuiUQ',
    address: "1773 W St. Mary's, #101",
    city: 'Tucson',
    state: 'AZ',
    zip: '85745',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nEmployer Directed Drug Screen\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJu1D2iXoHK4cRBF5BWR4fN1A',
    address: '1225 W Guadalupe',
    city: 'Mesa',
    state: 'AZ',
    zip: '85202',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJbXlKwsMLK4cReJGofDyopmc',
    address: '7281 E Earll Dr, Bldg A, #1',
    city: 'Scottsdale',
    state: 'AZ',
    zip: '85251',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ0YpJKB53K4cRWB-4jlvnbVs',
    address: '21803 N Scottsdale Rd, #A-210',
    city: 'Scottsdale',
    state: 'AZ',
    zip: '85255',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJU7-O-BF5K4cR9PHWsvVMY9c',
    address: '32551 N Scottsdale Rd',
    city: 'Scottsdale',
    state: 'AZ',
    zip: '85266',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJZaXR0tYuLYcRn7VtdlBSQ0w',
    address: '980 Willow Creek Rd, #203',
    city: 'Prescott',
    state: 'AZ',
    zip: '86301',
    servicesOffered:
      'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJFVf7uPsjLYcRjNcVTpNlseE',
    address: '3161 N Windsong Dr, #B',
    city: 'Prescott Valley',
    state: 'AZ',
    zip: '86314',
    servicesOffered:
      'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ-31gp_5LKocRKBt81JPy4k8',
    address: '37100 N Gantzel Rd, #112',
    city: 'San Tan Valley',
    state: 'AZ',
    zip: '85140',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJK1fzoDd1K4cRQ12l38mMYqY',
    address: '9445 E Ironwood Square Dr, #110',
    city: 'Scottsdale',
    state: 'AZ',
    zip: '85258',
    servicesOffered:
      'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJLXw9Byt61oYRktwkOoCWF2s',
    address: '1440 W Valencia, #130',
    city: 'Tucson',
    state: 'AZ',
    zip: '85746',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJCfII1w0SK4cRMRiSVWAlKco',
    address: '926 E McDowell Rd, #122',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85006',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJNViZtKdv1oYRxgA5laGcVqI',
    address: '603 N Wilmot Rd, #141',
    city: 'Tucson',
    state: 'AZ',
    zip: '85711',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJhTgKYKFv1oYR5ntO35ZKOc0',
    address: '6565 E Carondelet, #255',
    city: 'Tucson',
    state: 'AZ',
    zip: '85710',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nEmployer Directed Drug Screen\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ3VEwfw7LKIcRaVGPiqlVIn8',
    address: '2450 E Show Low Lake Rd, #3B',
    city: 'Show Low',
    state: 'AZ',
    zip: '85901',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJq0SylD0p14YR80vG4_e4W7I',
    address: '1150 S Highway 92, #E',
    city: 'Sierra Vista',
    state: 'AZ',
    zip: '85635',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJVeAMLU1CK4cRIrmjUcJnK-M',
    address: '10503 W Thunderbird Blvd, #105',
    city: 'Sun City',
    state: 'AZ',
    zip: '85351',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJazj4jyRbK4cR8nte7bgLNJM',
    address: '14420 W Meeker Blvd, Bldg A, #109',
    city: 'Sun City West',
    state: 'AZ',
    zip: '85375',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJkQM42VdVKocRnY3MCX8K1YM',
    address: '10450 E Riggs Rd, #109',
    city: 'Sun Lakes',
    state: 'AZ',
    zip: '85248',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJEVCpkKdaK4cRLYyx0kkyUIg',
    address: '15331 W Bell Rd, #110',
    city: 'Surprise',
    state: 'AZ',
    zip: '85374',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJIcDbgAxFK4cRizzAk-U5XU4',
    address: '13856 W Waddell Rd, #107',
    city: 'Surprise',
    state: 'AZ',
    zip: '85379',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJGXoNlckOK4cRGtYy59SUSyU',
    address: '1275 W Washington St, #109',
    city: 'Tempe',
    state: 'AZ',
    zip: '85281',
    servicesOffered: 'Routine Labs\nPediatric\nSemen Analysis\nGlucose Tolerance\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJHQ0Z6X4IK4cRp8h2uvHICGw',
    address: '2000 E Southern Ave, #101',
    city: 'Tempe',
    state: 'AZ',
    zip: '85282',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJSRufdSxw1oYRB3rxrXWnfRE',
    address: '630 N Alvernon Way, #200',
    city: 'Tucson',
    state: 'AZ',
    zip: '85711',
    servicesOffered:
      'Routine Labs\nPediatric\nSemen Analysis\nGlucose Tolerance\nInsurance Exam (Exam One)\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJfwnyHlFw1oYRQTCQWZ58uJM',
    address: '1940 E Broadway Blvd',
    city: 'Tucson',
    state: 'AZ',
    zip: '85719',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJxURxbnhl1oYReaeVRaVZnpk',
    address: '6360 E Golf Links Rd',
    city: 'Tucson',
    state: 'AZ',
    zip: '85730',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJ_37O5upBzoARttb3-hAzuig',
    address: '1751 W Hwy 95',
    city: 'Bullhead City',
    state: 'AZ',
    zip: '86442',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJVcr10IKpK4cR-QQ1bAni9Ag',
    address: '1060 E Ray Rd',
    city: 'Chandler',
    state: 'AZ',
    zip: '85225',
    servicesOffered: 'Routine Labs\nPediatric',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJxwx9JmxpK4cRjTfKsK9dxDs',
    address: '5310 W Thunderbird Rd, #200',
    city: 'Glendale',
    state: 'AZ',
    zip: '85306',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJfVzdp3FpK4cR8w23jGIHq5Y',
    address: '5605 W Eugie Ave, #104',
    city: 'Glendale',
    state: 'AZ',
    zip: '85304',
    servicesOffered: 'Routine Labs\nPediatric\nFingerstick PT/INR\nGlucose Tolerance\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJy_qLXmdoK4cRAJ71ldQ0_EA',
    address: '6320 W Union Hills Dr, #160',
    city: 'Glendale',
    state: 'AZ',
    zip: '85308',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJgciRla1BK4cRh96ktvhk8_o',
    address: '9980 W Glendale Ave, #120',
    city: 'Glendale',
    state: 'AZ',
    zip: '85307',
    servicesOffered: 'Routine Labs\nPediatric\nGlucose Tolerance\nQuest Health & Wellness\nDrop-Off Specimen Only',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'Sonora Quest',
    googlePlaceId: 'ChIJSbG_cB321oAR7CFkyAK5mhk',
    address: '2270 S Ridgeview Dr, #306',
    city: 'Yuma',
    state: 'AZ',
    zip: '85364',
    servicesOffered:
      'Routine Labs\nPediatric\nGlucose Tolerance\nInsurance Exam (Exam One)\nEmployer Directed Drug Screen\nQuest Health & Wellness\nDrop-Off Specimen Only\nCold Agglutinin/Cryoglobulin',
    notes: 'Spanish Translation\nHandicap Accessible',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJ1VojtWlpK4cRqaxBWtFXXPA',
    address: '13708 N 51st Ave',
    city: 'Glendale',
    state: 'AZ',
    zip: '85304',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJIZFaeitrK4cRVxUR3qKqE_k',
    address: '6409 W Glendale Ave, Suite K',
    city: 'Glendale',
    state: 'AZ',
    zip: '85301',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJIZFaeitrK4cRVxUR3qKqE_k',
    address: '13250 W. Van Buren, Ste. 106',
    city: 'Goodyear',
    state: 'AZ',
    zip: '85338',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJ33-ha3dxK4cRUGQ-hMF6w6s',
    address: '3305 E Greenway Rd, Suite 9',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85032',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJ2fGhYiKoK4cRSCGGpe7oN0M',
    address: '745 W Baseline Rd, Ste. 6',
    city: 'Mesa',
    state: 'AZ',
    zip: '85210',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJXzbVpUcSK4cRKYc9AzCaMUg',
    address: '505 W McDowell Rd, Bldg A',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85003',
    servicesOffered: '',
    notes: '',
  },
  {
    lab: 'LabXpress',
    googlePlaceId: 'ChIJdVkhGTl61oYRJcV-tQNc7EM',
    address: '5650 S. 12th Ave, Suite 132',
    city: 'Tucson',
    state: 'AZ',
    zip: '85706',
    servicesOffered: '',
    notes: '',
  },
];
