logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]
  dashboard = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedbydefault = false
  watch = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[acme]
  email = "bart@getlabs.com"
  onHostRule = true
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
    [acme.dnsChallenge]
      provider = "gcloud"
      delayBeforeCheck = 160
      resolvers = ["8.8.8.8:53"]
