name: Build and Push to GCR

on:
  push:
    branches:
      - master
      - develop

# Enable this once we run automated tests on pull requests
#  pull_request:
#    branches:
#      - master
#      - develop

env:
  GKE_PROJECT: getlabs-admin
  IMAGE: getlabs-api

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish Image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:

      # Checkout source code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 290.0.1
          service_account_key: ${{ secrets.GKE_KEY }}

      # Configure docker to use gcloud cli as credential helper
      # - run: gcloud auth configure-docker
      # This is temporary until docker/build-push-action@v2
      - name: Generate Access Token
        id: generate-access-token
        run: echo "::set-output name=token::$(gcloud auth print-access-token)"

      # Checkout private actions repo
      - name: Checkout GitHub actions
        uses: actions/checkout@v2
        with:
          repository: getlabs-app/actions
          path: actions
          token: ${{ secrets.GITHUB_PAT }}

      # Create valid tag slugs
      - name: Create Tag
        id: create-tag
        uses: ./actions/create-docker-tag

      # Read build parameters
      - name: Read Build Parameters
        id: read-build-params
        uses: ./actions/read-docker-build-params

      # Build and push the docker image
      - name: Build
        uses: docker/build-push-action@v1
        with:
          registry: gcr.io
          repository: getlabs-admin/getlabs-api
          username: oauth2accesstoken
          password: ${{ steps.generate-access-token.outputs.token }}
          tags: ${{ steps.create-tag.outputs.tag }},${{ steps.create-tag.outputs.latest }}
          build_args: sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }},${{ steps.read-build-params.outputs.build-args }}
        env:
          DOCKER_BUILDKIT: 1
