export enum AppointmentCancellationReason {
  NoAnswer = 'no-answer',
  NoConfirm = 'no-confirm',
  PatientRequested = 'patient-requested',
  PatientSelfRequested = 'patient-self-requested',
  PatientProvidedIncorrectInfo = 'patient-incorrect-info',
  PatientBookedInLabAppointment = 'patient-booked-inlab-appointment',
  PatientUnderage = 'patient-underage',
  PatientFailedToFast = 'patient-failed-to-fast',
  LabOrderUnclear = 'lab-order-unclear',
  SpecialistInsufficientSupplies = 'specialist-insufficient-supplies',
  SpecialistUnavailable = 'specialist-unavailable',
  SpecialistNoShow = 'specialist-no-show',
  LogisticsIssue = 'logistics-issue',
  OpsInsufficientSupplies = 'ops-insufficient-supplies',
  UnsupportedTest = 'unsupported-test',
  NoLabOrder = 'no-lab-order',
  Rebooked = 'rebooked',
  Duplicate = 'duplicate',
  Other = 'other',
}
